### PR TITLE
Update icons to work properly with Chrome Store

### PR DESCRIPTION
**Pull request by Stvad**

### CODE REVIEW

**Comment by fuddl** [comment]
😐

**Comment by Stvad** [comment]
we do what must be done 😬

**Comment by fuddl** [comment]
Is there an issue to follow up on?

**Comment by Stvad** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=29683 is the chrome issue, looking at its history, I'm a bit skeptical of it's being resolved soon =\

**Pull request merged**
