### PR TITLE
#66 remember the sidebar width

### PR DESCRIPTION
**Pull request by Stvad**

### CODE REVIEW

**Comment by fuddl** [comment]
so the width is consistent even when you navigate. that's great but

- [ ]  the width is reset as soon as you open a new tab or close the browser
- [ ]  the location (left or right) should also be remembered
- [ ]  the slide transition should not occur upon navigation

**Comment by Stvad** [comment]
> the width is reset as soon as you open a new tab or close the browser

hmm, the state is currently local to the tab by design. on reflection that does seem to narrow for parameters like width - open state def should be scoped to the tab.

not sure if the full browser is an appropriate dimension though (`useBrowserLocalState` is the answer then)?  I think the native sidebar scopes that to browser window, so we may want to follow that?

**Comment by Stvad** [comment]
Pushed an update for the first 2, not entirely sure what you mean by the third one?

**Comment by fuddl** [comment]
@Stvad sorry, i got ahead of myself. If we want to emulate the behavior of the native sidebar – which is i think what we are aiming for (?) – the sidebar should stay open when navigating. Let me know if you agree. [I updated the list.](https://github.com/fuddl/wd/pull/69#issuecomment-1059717454)

**Comment by Stvad** [comment]
hmm. it does stay open, but afaik we can't make it so it's not re-rendered as it's actually part of the page. Also, IMO that's outside of scope for this PR

**Comment by fuddl** [comment]
udnerstood

**Pull request merged**
