### PR TITLE
Add: make link resolution async, to speed up the process and make it more robust to any given resolution failing

### PR DESCRIPTION
**Pull request by Stvad**

### CODE REVIEW

**Comment by fuddl** [comment]
sure lets try

**Comment by fuddl** [comment]
i noticed that this crashes the resolution process when there are too many links on the page. Maybe the wikidata api refused to answer too many callback at once.

I propose to go back to synchronous resolution and make the process smarter, so that only [links currently in the viewport](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) get resolved.

**Comment by Stvad** [comment]
Hmm, can you provide an example page and what errors do you see?

> Maybe the wikidata api refused to answer too many requests at once.

do we get an actual error from wikidata?

I don't think "links in the viewport" is actually what we want here though - like I want to collect any information that is potentially relevant from the page.  

Also, maybe create a separate issue for the follow-up?

**Comment by fuddl** [comment]
jap. sorry. this was a false alarm

**Pull request merged**
