### PR TITLE
Set up bundling to enable 3p dependency usage

### PR DESCRIPTION
**Pull request by Stvad**
This adds Parcel 2 bundler setup for the package to enable using 3p dependencies in the future. It's based on setup in https://github.com/fregante/browser-extension-template 

### Changes
Besides actually adding bundler this:
- moves source into `src` subdirectory to make it easier to point bundler at subset of things and search in non-generated source
- makes a few changes into how things are imported & manifest to ensure that bundler picks all the relevant things up

### Challenges
Main source of issues in setting this up was that bundler can't understand that it needs to pick up resources when they are referenced in a dynamic manner (e.g. creating a style tag and referencing to an underlying CSS as a string vs direct import [like most components do](https://github.com/fuddl/wd/blob/master/sidebar/components/bouncer/bouncer.tpl.js#L22)

I've worked around that by specifying those files in the `web_accessible_resources` part of the manifest, which has effect of telling the bundler that it needs to pack those resources explicitly.   

**It's a bit hard to tell if I covered all the resources, though, so I'd appreciate you paying special attention to this**

## Todo for this PR
- [x] Update Readme for new dev instructions
- [x] Add more context on changes and challenges
- [x] ~Example dependency usage~
  - Decided not to do that for now, as it's a bit hard without having a broader context for the codebase, some interesting options can include:
    -  https://www.npmjs.com/package/wikidata-sdk for wikidata queries
    - I've removed options stuff provided by https://github.com/fregante/browser-extension-template but, may be interesting to bring it back if there is a use-case
    - a random note for language guessing - there is apparently a built-in browser extension functionality for that https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/detectLanguage

### CODE REVIEW

**Comment by fuddl** [comment]
The `browser_action.default_icon` is there:

But the active state (`/src/icons/wd.svg`) seems to be missing:

**Comment by Stvad** [comment]
That's a weird one, it's referenced both statically (with manifest) and dynamically (via seticon & string) and because of that the workaround with adding it to manifest does not work 🤔.

**Comment by Stvad** [comment]
Pushed an update for that, it's probably generally a better approach to reference icons via import vs doing it with string path reference

**Comment by Stvad** [comment]
Hrm, just noticed that "add" view has broken CSS now, which is weird, becasue it was working ok for me at some prev iteration 🤔. Checking that out now

**Comment by Stvad** [comment]
Seems to be another case of both dynamic and direct usage (in html files, and in one place dynamic tag creation)

**Comment by Stvad** [comment]
As far as I can tell it was only affecting `remark` and `ensign` components

**Pull request merged**
